### ISSUE TITLE
How to train, run this model

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [mschrader15/reinforcement-learning-sumo#1]
Hello
Thank you for sharing your code.
But Could you show me how to train and test this model?
Thanks

**Comment by mschrader15** [comment]
Hi @TrinhTuanHung2021 , thanks for looking at the repository! 

Do you have a specific goal in mind? There are several RL + SUMO codebases available and I want to make sure that mine is the right one for you to use first.

**Comment by TrinhTuanHung2021** [comment]
> 

> Hi @TrinhTuanHung2021 , thanks for looking at the repository!
> 
> Do you have a specific goal in mind? There are several RL + SUMO codebases available and I want to make sure that mine is the right one for you to use first.


Thank you for sharing the coding. I already know Sumo and flow for applying DRL to traffic simulation.
PPO is an interesting topic for traffic but very difficult. So I think to understand your model deeply, there should be specific and detailed instructions attached. You can clearly share every step from training to testing for user convenience

**Comment by mschrader15** [comment]
There is a more detailed write-up here: https://maxschrader.io/reinforcement-learning-and-sumo 

Let me know if you want more information!
