### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [mschrader15/reinforcement-learning-sumo#7]
Hello

I only run your models with python==3.8 and ray==1.11.0
Please update them in `requirements.txt`

After 1 day of training, my computer was out of memory with ray so I coud not have final resutls 
The configurations of my PC: i9, ram=32gb

**Comment by TrinhTuanHung2021** [comment]
== Status ==
Current time: 2022-08-24 15:01:03 (running for 04:32:04.10)
Memory usage on this node: 30.9/33.4 GiB: ***LOW MEMORY*** less than 10% of the memory on this node is available for use. This can cause unexpected crashes. Consider reducing the memory used by your application or reducing the Ray object store size by setting `object_store_memory` when calling `ray.init`.
Using FIFO scheduling algorithm.
Resources requested: 2.0/16 CPUs, 0/0 GPUs, 0.0/18.59 GiB heap, 0.0/9.3 GiB objects
Result logdir: /home/osboxes/ray_results/ES-updated
Number of trials: 1/1 (1 RUNNING)

**Comment by TrinhTuanHung2021** [comment]
I add `ray.init(object_store_memory=200**9)` in rllib.py

**Comment by mschrader15** [comment]
Thanks for the information @TrinhTuanHung2021 ! 

Do you feel comfortable making a pull request with both the requirements update as well object store update? I will merge it into the main code if so
